#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
#ifndef VIDEOEDITORLIB_SWIFT_H
#define VIDEOEDITORLIB_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import AVFoundation;
@import CoreFoundation;
@import CoreImage;
@import CoreLocation;
@import CoreMedia;
@import Foundation;
@import GiphyUISDK;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoEditorLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS("_TtC14VideoEditorLib8ABBorder")
@interface ABBorder : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC14VideoEditorLib14ABEndIndicator")
@interface ABEndIndicator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIEvent;

SWIFT_CLASS("_TtC14VideoEditorLib19ABProgressIndicator")
@interface ABProgressIndicator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib16ABStartIndicator")
@interface ABStartIndicator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib19ABThumbnailsManager")
@interface ABThumbnailsManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib10ABTimeView")
@interface ABTimeView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib13ABVideoHelper")
@interface ABVideoHelper : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class UIPanGestureRecognizer;

SWIFT_CLASS("_TtC14VideoEditorLib18ABVideoRangeSlider")
@interface ABVideoRangeSlider : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)startDraggedWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)endDraggedWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)progressDraggedWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)viewDraggedWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)layoutSubviews;
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib15AKAudioRecorder")
@interface AKAudioRecorder : NSObject
- (void)updateDuration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class AVAudioRecorder;

@interface AKAudioRecorder (SWIFT_EXTENSION(VideoEditorLib)) <AVAudioRecorderDelegate>
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
- (void)audioRecorderEncodeErrorDidOccur:(AVAudioRecorder * _Nonnull)recorder error:(NSError * _Nullable)error;
@end

@class AVAudioPlayer;

@interface AKAudioRecorder (SWIFT_EXTENSION(VideoEditorLib)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer * _Nonnull)player error:(NSError * _Nullable)error;
@end



@class UIWindow;
@class UIApplication;
@class UISceneSession;
@class UISceneConnectionOptions;
@class UISceneConfiguration;

SWIFT_CLASS("_TtC14VideoEditorLib11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (UISceneConfiguration * _Nonnull)application:(UIApplication * _Nonnull)application configurationForConnectingSceneSession:(UISceneSession * _Nonnull)connectingSceneSession options:(UISceneConnectionOptions * _Nonnull)options SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=13.0);
- (void)application:(UIApplication * _Nonnull)application didDiscardSceneSessions:(NSSet<UISceneSession *> * _Nonnull)sceneSessions SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib12AudioManager")
@interface AudioManager : NSObject
- (void)updateElapsedTimeLabel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AudioManager (SWIFT_EXTENSION(VideoEditorLib)) <AVAudioRecorderDelegate>
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
@end


SWIFT_CLASS("_TtC14VideoEditorLib19CameraConfiguration")
@interface CameraConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCapturePhotoOutput;
@class AVCapturePhoto;

@interface CameraConfiguration (SWIFT_EXTENSION(VideoEditorLib)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhoto:(AVCapturePhoto * _Nonnull)photo error:(NSError * _Nullable)error;
@end



SWIFT_CLASS("_TtC14VideoEditorLib14CaptureSession")
@interface CaptureSession : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface CaptureSession (SWIFT_EXTENSION(VideoEditorLib)) <AVCaptureAudioDataOutputSampleBufferDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class UILabel;

SWIFT_CLASS("_TtC14VideoEditorLib26CategoryCollectionViewCell")
@interface CategoryCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;
@class TextViewMaster;

SWIFT_CLASS("_TtC14VideoEditorLib17ChatBottomToolbar")
@interface ChatBottomToolbar : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified addPhotoButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified captionView;
@property (nonatomic, weak) IBOutlet TextViewMaster * _Null_unspecified captionTextView;
- (void)sendButtonClick;
- (void)addPhotoClick;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class NSNotification;

@interface ChatBottomToolbar (SWIFT_EXTENSION(VideoEditorLib))
- (void)keyboardWillShowWithNotification:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHideWithNotification:(NSNotification * _Nonnull)notification;
@end


SWIFT_PROTOCOL("_TtP14VideoEditorLib22TextViewMasterDelegate_")
@protocol TextViewMasterDelegate <UITextViewDelegate>
@optional
- (BOOL)growingTextViewWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (void)growingTextViewShouldReturnWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView;
- (void)growingTextViewWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView willChangeHeight:(CGFloat)height;
- (void)growingTextViewWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView didChangeHeight:(CGFloat)height;
@end


@interface ChatBottomToolbar (SWIFT_EXTENSION(VideoEditorLib)) <TextViewMasterDelegate>
- (void)growingTextViewWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView willChangeHeight:(CGFloat)height;
- (BOOL)growingTextViewWithGrowingTextView:(TextViewMaster * _Nonnull)growingTextView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib12XibBasedView")
@interface XibBasedView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;

SWIFT_CLASS("_TtC14VideoEditorLib11ChatTopView")
@interface ChatTopView : XibBasedView
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified photoView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIFont;
@class UILongPressGestureRecognizer;

SWIFT_CLASS("_TtC14VideoEditorLib14CountdownTimer")
@interface CountdownTimer : UIView
@property (nonatomic) IBInspectable CGFloat lineWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull lineColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull trailLineColor;
@property (nonatomic) IBInspectable BOOL isLabelHidden;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable labelFont;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable labelTextColor;
@property (nonatomic, copy) IBInspectable NSString * _Nullable timerFinishingText;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (void)takePhoto;
- (void)startVideoRecordingWithGestureReconizer:(UILongPressGestureRecognizer * _Nonnull)gestureReconizer;
@end


SWIFT_PROTOCOL("_TtP14VideoEditorLib22CountdownTimerDelegate_")
@protocol CountdownTimerDelegate
@optional
- (void)timerDidUpdateCounterValueWithSender:(CountdownTimer * _Nonnull)sender newValue:(NSInteger)newValue;
- (void)timerDidStartWithSender:(CountdownTimer * _Nonnull)sender;
- (void)timerDidPauseWithSender:(CountdownTimer * _Nonnull)sender;
- (void)timerDidResumeWithSender:(CountdownTimer * _Nonnull)sender;
- (void)timerDidEndWithSender:(CountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
- (void)takePhoto;
- (void)startVideoRecordingWithGestureReconizer:(UILongPressGestureRecognizer * _Nonnull)gestureReconizer;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib12CustomButton")
@interface CustomButton : UIButton
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull defaultBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull defaultTextColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedTextColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
@end

@class UITextView;
@class UIStackView;

SWIFT_CLASS("_TtC14VideoEditorLib15CustomInputView")
@interface CustomInputView : XibBasedView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified timeView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified dateStackView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified timeStackView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CustomInputView (SWIFT_EXTENSION(VideoEditorLib)) <UITextViewDelegate>
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib11CustomLabel")
@interface CustomLabel : UILabel
@property (nonatomic) IBInspectable CGFloat cornerRadius;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib16DesignableButton")
@interface DesignableButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib14DesignableView")
@interface DesignableView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@end


SWIFT_CLASS("_TtC14VideoEditorLib12DismissPopup")
@interface DismissPopup : XibBasedView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified descLabel;
- (IBAction)discardClicked:(UIButton * _Nonnull)sender;
- (IBAction)cancelClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class Pallet;
@class ExcelliFont;
@class SwiftlySlider;
@class NSLayoutConstraint;
@class UITapGestureRecognizer;
@class UIGestureRecognizer;

IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib13DrawingCanvas")
@interface DrawingCanvas : XibBasedView <UIGestureRecognizerDelegate>
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
@property (nonatomic, weak) IBOutlet Pallet * _Null_unspecified pallet;
@property (nonatomic, weak) IBOutlet ExcelliFont * _Null_unspecified font;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified tickButton;
@property (nonatomic, weak) IBOutlet SwiftlySlider * _Null_unspecified volumeSlider;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified palletBottomConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified fontBottomConstraint;
- (void)keyboardWillShow:(NSNotification * _Nullable)notification;
- (void)keyboardWillHide:(NSNotification * _Nullable)notification;
- (void)handleTap:(UITapGestureRecognizer * _Nonnull)gesture;
- (void)handlePan:(UIPanGestureRecognizer * _Nonnull)gesture;
- (IBAction)doneButtonClicked;
- (IBAction)stackButtonClicked:(UIButton * _Nonnull)sender;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface DrawingCanvas (SWIFT_EXTENSION(VideoEditorLib)) <UITextViewDelegate>
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib25EffectsCollectionViewCell")
@interface EffectsCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified effectIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC14VideoEditorLib11EffectsView")
@interface EffectsView : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified effectsCollectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayout;
@class NSIndexPath;

@interface EffectsView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface EffectsView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface EffectsView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIProgressView;
@class NSBundle;

SWIFT_CLASS("_TtC14VideoEditorLib27ExcelliCameraViewController")
@interface ExcelliCameraViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified previewView;
@property (nonatomic, weak) IBOutlet UIProgressView * _Null_unspecified progressView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified previewBottomConstraint;
@property (nonatomic, weak) IBOutlet CountdownTimer * _Null_unspecified shootView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified topView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified topContainer;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomShadowView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified toolbarView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified toolbarLabelsView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified remainingTimeLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified speedButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified lockView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified songNameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified speedLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified timeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified beautyLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified songLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified photoPreview;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified songLabelWidthConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified songLabelTrailingConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified toolBarBottomConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified switchViewCenterConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified instructionLabelHeightConstraint;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified switchOptionsView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified galleryView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified galleryButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified nextView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified storyButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified timelineButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified flicksButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified flashButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cameraButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified toggleButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified ratioButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified beautyButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified songButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified hintLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomOptionsView;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface ExcelliCameraViewController (SWIFT_EXTENSION(VideoEditorLib)) <UITextViewDelegate>
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
@end




@interface ExcelliCameraViewController (SWIFT_EXTENSION(VideoEditorLib)) <CountdownTimerDelegate>
- (void)takePhoto;
- (void)startVideoRecordingWithGestureReconizer:(UILongPressGestureRecognizer * _Nonnull)gestureReconizer;
- (void)timerDidUpdateCounterValueWithSender:(CountdownTimer * _Nonnull)sender newValue:(NSInteger)newValue;
- (void)timerDidEndWithSender:(CountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
@end




IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib11ExcelliFont")
@interface ExcelliFont : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified fontCollectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ExcelliFont (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ExcelliFont (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface ExcelliFont (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib13ExcelliPlayer")
@interface ExcelliPlayer : NSObject
- (void)playerDidFinishPlayingWithSender:(NSNotification * _Nonnull)sender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib4File")
@interface File : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UISlider;

SWIFT_CLASS("_TtC14VideoEditorLib16FilterAndVisuals")
@interface FilterAndVisuals : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified filterCollectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified buttonStackView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified filterOrVisualButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified editOrTransButton;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified sliderProgressView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified sliderView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified sliderLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified undoButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified reviewButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified prevButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified nextButton;
- (void)longPressWithRecognizer:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (IBAction)cancelButtonClick;
- (IBAction)doneButtonClick;
- (IBAction)undoButtonClick;
- (IBAction)prevButtonClick;
- (IBAction)nextButtonClick;
- (IBAction)stackButtonsClicked:(UIButton * _Nonnull)sender;
- (IBAction)sliderValueChanged:(UISlider * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface FilterAndVisuals (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface FilterAndVisuals (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface FilterAndVisuals (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib24FilterCollectionViewCell")
@interface FilterCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified filterIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified iconHeightConstraint;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib22FontCollectionViewCell")
@interface FontCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fontLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib8GridView")
@interface GridView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14VideoEditorLib17LayoutOptionsView")
@interface LayoutOptionsView : XibBasedView
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (IBAction)layoutOptionsClicked:(CustomButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC14VideoEditorLib18LinkViewController")
@interface LinkViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified clearButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified linkField;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)saveButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)clearButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface LinkViewController (SWIFT_EXTENSION(VideoEditorLib)) <UITextFieldDelegate>
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end

@class UITableView;
@class UITableViewCell;

SWIFT_CLASS("_TtC14VideoEditorLib22LocationViewController")
@interface LocationViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified locationView;
@property (nonatomic, strong) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (IBAction)turnOnLocationClicked:(UIButton * _Nonnull)sender;
- (IBAction)cancelClicked:(UIButton * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocationManager;
@class CLLocation;

@interface LocationViewController (SWIFT_EXTENSION(VideoEditorLib)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
@end



SWIFT_CLASS("_TtC14VideoEditorLib15OptiVideoEditor")
@interface OptiVideoEditor : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditorLib6Pallet")
@interface Pallet : XibBasedView
@property (nonatomic, copy) IBOutletCollection(DesignableButton) NSArray<DesignableButton *> * _Null_unspecified buttons;
- (IBAction)colorButtonPressed:(DesignableButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib18PhotoThumbnailCell")
@interface PhotoThumbnailCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified thumbnailView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib18PhotoThumbnailView")
@interface PhotoThumbnailView : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified thumbnailCollectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface PhotoThumbnailView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface PhotoThumbnailView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface PhotoThumbnailView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScene;

SWIFT_CLASS("_TtC14VideoEditorLib13SceneDelegate") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (void)scene:(UIScene * _Nonnull)scene willConnectToSession:(UISceneSession * _Nonnull)session options:(UISceneConnectionOptions * _Nonnull)connectionOptions;
- (void)sceneDidDisconnect:(UIScene * _Nonnull)scene;
- (void)sceneDidBecomeActive:(UIScene * _Nonnull)scene;
- (void)sceneWillResignActive:(UIScene * _Nonnull)scene;
- (void)sceneWillEnterForeground:(UIScene * _Nonnull)scene;
- (void)sceneDidEnterBackground:(UIScene * _Nonnull)scene;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITouch;

SWIFT_CLASS("_TtC14VideoEditorLib22SetTimerViewController")
@interface SetTimerViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified timerView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified durationLabel;
@property (nonatomic, weak) IBOutlet ABVideoRangeSlider * _Null_unspecified rangeSlider;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified threeSecButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified tenSecButton;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (void)dragTracker:(UIPanGestureRecognizer * _Nonnull)sender;
- (void)dismissViewOnTapWithTapGesture:(UIGestureRecognizer * _Nonnull)tapGesture;
- (IBAction)timerDurationClicked:(UIButton * _Nonnull)sender;
- (IBAction)startTimeClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14VideoEditorLib17SongTableViewCell")
@interface SongTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified songIcon;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified trimButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified title;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified composer;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified selectButton;
- (void)awakeFromNib;
- (IBAction)selectButtonClick:(UIButton * _Nonnull)sender;
- (IBAction)trimButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib15SongsHeaderView")
@interface SongsHeaderView : UITableViewHeaderFooterView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified categoryCollectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified searchView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified searchTextField;
- (void)awakeFromNib;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SongsHeaderView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SongsHeaderView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface SongsHeaderView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib16SongsViewAdapter")
@interface SongsViewAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface SongsViewAdapter (SWIFT_EXTENSION(VideoEditorLib)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SongsViewAdapter (SWIFT_EXTENSION(VideoEditorLib)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib19SongsViewController")
@interface SongsViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified songTableView;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (IBAction)backButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC14VideoEditorLib14SoundTrackView")
@interface SoundTrackView : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified musicCollectionView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified soundtrack;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified volume;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified volumeView;
- (IBAction)sliderValueChanged:(UISlider * _Nonnull)sender;
- (IBAction)trimMusic:(UIButton * _Nonnull)sender;
- (IBAction)stackviewButtonsClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SoundTrackView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SoundTrackView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface SoundTrackView (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib9SpeedView")
@interface SpeedView : XibBasedView
@property (nonatomic, copy) IBOutletCollection(UIButton) NSArray<UIButton *> * _Null_unspecified speedButtons;
- (IBAction)speedOptionClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib14StickerAdapter")
@interface StickerAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class UICollectionReusableView;

@interface StickerAdapter (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface StickerAdapter (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface StickerAdapter (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib25StickerCollectionViewCell")
@interface StickerCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified stickerIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified stickerLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib12StickerPopup")
@interface StickerPopup : XibBasedView
- (IBAction)setDurationClicked:(UIButton * _Nonnull)sender;
- (IBAction)editClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib17StickerSearchView")
@interface StickerSearchView : UICollectionReusableView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified searchView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified searchField;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface StickerSearchView (SWIFT_EXTENSION(VideoEditorLib)) <UITextFieldDelegate>
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib21StickerViewController")
@interface StickerViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified stickerCollectionView;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (void)dismissViewOnTapWithTapGesture:(UIGestureRecognizer * _Nonnull)tapGesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class GiphyViewController;
@class GPHMedia;

@interface StickerViewController (SWIFT_EXTENSION(VideoEditorLib)) <GiphyDelegate>
- (void)didSearchFor:(NSString * _Nonnull)term;
- (void)didSelectMediaWithGiphyViewController:(GiphyViewController * _Nonnull)giphyViewController media:(GPHMedia * _Nonnull)media;
- (void)didDismissWithController:(GiphyViewController * _Nullable)controller;
@end


SWIFT_CLASS("_TtC14VideoEditorLib18StoryBottomToolbar")
@interface StoryBottomToolbar : XibBasedView
- (IBAction)saveStory;
- (IBAction)shareStory;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib13StoryGradient")
@interface StoryGradient : XibBasedView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified gradientCollectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface StoryGradient (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface StoryGradient (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface StoryGradient (SWIFT_EXTENSION(VideoEditorLib)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditorLib12StoryToolbar")
@interface StoryToolbar : XibBasedView
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified gradientButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified optionFour;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified optionBottomConstraint;
- (IBAction)toolbarOptionsClicked:(UIButton * _Nonnull)sender;
- (IBAction)gradientClicked:(CustomButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib13SwiftlySlider")
@interface SwiftlySlider : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)handlePan:(UIPanGestureRecognizer * _Nonnull)gesture;
- (void)drawRect:(CGRect)rect;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC14VideoEditorLib14TextViewMaster")
@interface TextViewMaster : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
@end


@interface TextViewMaster (SWIFT_EXTENSION(VideoEditorLib)) <TextViewMasterDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end




@class CIImage;

SWIFT_CLASS("_TtC14VideoEditorLib15ThresholdFilter")
@interface ThresholdFilter : CIFilter
@property (nonatomic, readonly, strong) CIImage * _Null_unspecified outputImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib16TouchThroughView")
@interface TouchThroughView : UIView
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib23TrimAudioViewController")
@interface TrimAudioViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified trimView;
@property (nonatomic, weak) IBOutlet ABVideoRangeSlider * _Null_unspecified rangeSlider;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified chunkDurationLabel;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (void)dismissViewOnTapWithTapGesture:(UIGestureRecognizer * _Nonnull)tapGesture;
- (IBAction)selectAudioButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC14VideoEditorLib9TrimMedia")
@interface TrimMedia : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class VideoThumbnail;

SWIFT_CLASS("_TtC14VideoEditorLib13TrimVideoView")
@interface TrimVideoView : XibBasedView
@property (nonatomic, weak) IBOutlet VideoThumbnail * _Null_unspecified thumbnailView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified optionView;
- (IBAction)onButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib23TrimVideoViewController")
@interface TrimVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified previewView;
@property (nonatomic, weak) IBOutlet UIProgressView * _Null_unspecified progressView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified durationLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified speedButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified shadowView;
@property (nonatomic, weak) IBOutlet ABVideoRangeSlider * _Null_unspecified rangeSlider;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneButton;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified rangeSliderBottomConstraint;
@property (nonatomic, weak) IBOutlet VideoThumbnail * _Null_unspecified thumbnailView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified topContainer;
- (void)viewDidLoad;
- (void)playVideoWithTapGesture:(UITapGestureRecognizer * _Nonnull)tapGesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end















@interface UITextView (SWIFT_EXTENSION(VideoEditorLib)) <UITextViewDelegate>
/// Resize the placeholder when the UITextView bounds change
@property (nonatomic) CGRect bounds;
/// When the UITextView did change, show or hide the label based on if the UITextView is empty or not
/// \param textView The UITextView that got updated
///
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
@end





SWIFT_CLASS("_TtC14VideoEditorLib26VideoEditingViewController")
@interface VideoEditingViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified previewImageView;
@property (nonatomic, weak) IBOutlet DrawingCanvas * _Null_unspecified drawingCanvas;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified deleteButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified toolbarView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomToolbarView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified buttonStackView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified songNameLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified topContainer;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified containerLeftConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified containerRightConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified containerBottomConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified songLabelWidthConstraint;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)keyboardWillChangeFrame:(NSNotification * _Nonnull)notification;
- (void)tapGestureHandler;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







@class UIImage;

@interface VideoEditingViewController (SWIFT_EXTENSION(VideoEditorLib))
- (void)image:(UIImage * _Nonnull)image didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(void const * _Nonnull)contextInfo;
@end







@class UIPinchGestureRecognizer;
@class UIRotationGestureRecognizer;
@class UIScreenEdgePanGestureRecognizer;

@interface VideoEditingViewController (SWIFT_EXTENSION(VideoEditorLib)) <UIGestureRecognizerDelegate>
- (void)panGesture:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (void)pinchGesture:(UIPinchGestureRecognizer * _Nonnull)recognizer;
- (void)rotationGesture:(UIRotationGestureRecognizer * _Nonnull)recognizer;
- (void)tapGesture:(UITapGestureRecognizer * _Nonnull)recognizer;
- (void)longPressGesture:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (void)screenEdgeSwiped:(UIScreenEdgePanGestureRecognizer * _Nonnull)recognizer;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)scaleEffectWithView:(UIView * _Nonnull)view;
- (NSArray<UIImageView *> * _Nonnull)subImageViewsWithView:(UIView * _Nonnull)view SWIFT_WARN_UNUSED_RESULT;
@end

@class NSURL;

@interface VideoEditingViewController (SWIFT_EXTENSION(VideoEditorLib))
- (IBAction)backButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)toolbarButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)bottomToolbarButtonClicked:(UIButton * _Nonnull)sender;
- (void)playVideoAfterViewHiddenWithUrl:(NSURL * _Nonnull)url;
@end


SWIFT_CLASS("_TtC14VideoEditorLib14VideoGenerator")
@interface VideoGenerator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib19VideoGeneratorError")
@interface VideoGeneratorError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14VideoEditorLib14VideoThumbnail")
@interface VideoThumbnail : XibBasedView
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified thumbnailView;
- (void)thumbnailClicked:(UITapGestureRecognizer * _Nonnull)recognizer;
- (IBAction)doneButtonPressed:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditorLib18VoiceRecordingView")
@interface VoiceRecordingView : XibBasedView
@property (nonatomic, weak) IBOutlet ABVideoRangeSlider * _Null_unspecified thumbnailSlider;
- (void)updateDuration;
- (void)updateSliderProgress;
- (IBAction)recordingButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)undoClicked:(UIButton * _Nonnull)sender;
- (IBAction)cancelClicked:(UIButton * _Nonnull)sender;
- (IBAction)doneClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
